[project]
name = "goosedns-client"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "logging>=0.4.9.6",
    "paramiko>=3.5.1",
    "pyyaml>=6.0.2",
    "requests>=2.32.3",
    "scp>=0.15.0",
]
